name: PR Linters and Test
on:
  push:
    branches:
      - 'equipo5'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Ejecutar prettier
        working-directory: front
        run: npm run prettier
      - name: Pasar test front
        working-directory: front
        run: npm run test
      - name: Generar build
        working-directory: front
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03X26V20oiYnHCgYIARAAGAMSNwF-L9Ir_toA5GlAYC25JrsK9TYJnrNfi6A_Gr8cpdNNMWHOQ7lLc_9cqxKF-uHOBcgt7uRp5Eg
        