name: PR Linters and Test
on:
  push:
    branches:
      - 'equipo1_miriam'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias front
        working-directory: front
        run: npm ci
      - name: Pasar test front
        working-directory: front
        run: npm run test
      - name: Instalar dependencias back
        working-directory: api
        run: npm ci
      - name: Pasar test back
        working-directory: api
        run: npm run test
      - name: Generar build
        working-directory: front
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03nvbGEm8mQImCgYIARAAGAMSNwF-L9IrL_cGnsnB5EphxoiCP1biB17ho0zr6j4-YycSP_CR7rmzPVkr_LRXFp-WhuPYABkR6og
