name: PR Linters and Test
on:
  push:
    branches:
      - 'git_hooks_marcos'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Ejecuta el prettier
        working-directory: front
        run: npm run prettier
      - name: Ejecuta los test
        working-directory: front
        run: CI=True npm run test