name: PR Linters and Test
on:
  push:
    branches:
      - 'equipo2_a'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Prettier Check
        working-directory: front
        run: npm run prettier
      #- name: Prettify code
      #  uses: creyD/prettier_action@v3.1
      #  with:
          # This part is also where you can pass other options, for example:
          #prettier_options: --write **/*.{js,md}
      #    dry: true
      - name: Ejecutar tests
        working-directory: front
        run: npm run precommit-test
      - name: Generar build
        working-directory: front
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03NtNFwchAhlTCgYIARAAGAMSNwF-L9IrDI1_XptA0KR-J6n9krhbchO72CduKFvjCkoa2UyNNZQZLnlh81kB8e65BmZeoMlYFaI