name: PR Linters and Test
on:
  push:
    branches:
      - 'equipo2_a'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Ejecutar linter
        working-directory: front
        run: lint-staged
      - name: Ejecutar tests
        working-directory: front
        run: npm run precommit-test


        
