# This is a basic workflow to help you get started with Actions

name: CI-prettier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ equipo6-ANAgithooks ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias # para que no haya problemas
        working-directory: front # lo ponemos fuera xq aqui specficamos
        run: yarn install --frozen-lockfile

      # Runs the prettier I have in my project
      - name: Run prettier
        working-directory: front
        run: yarn run prettier

      # Runs the tests in the front
      - name: Run tests del front
        working-directory: front
        run: yarn run test --env=jest-environment-jsdom-sixteen

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03WEWS7MOMXE5CgYIARAAGAMSNwF-L9IrTDAQJWDtv8jcLizfhFGkmLDJQZkzkzEicXwwl0rweiubobNp3vtO0SgCoV1EISbVErQ