name: Node.js CI

on: 
  push:
    branches:
      - equipo4

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias generales
        run: npm install
      - name: Instalar dependencias api
        working-directory: ./api
        run: npm install
      - name: Instalar dependencias front
        working-directory: ./front
        run: npm install
      - name: Ejecuto prettier
        run: npm run prettier
      - name: Ejecuto los test del API
        working-directory: ./api
        run: npm run test
      - name: Ejecuto los test del API
        working-directory: ./front
        run: npm run test